# Случайные вектор и совместное распределение

In [40]:
import numpy as np

import matplotlib.pyplot as plt

from IPython.display import display
from tabulate import tabulate

In [41]:
x = np.arange(0, 3)
y = np.arange(0, 3)

rng_prob = np.random.default_rng(2)
cum_probs = rng_prob.uniform(low=0, high=1, size=len(x)*len(y)-1).round(3)
cum_probs = np.append(arr=cum_probs, values=[0,1])
probs = np.reshape( np.diff(np.sort(cum_probs)), (len(x), len(y)) )

# print(probs)

# distr_law = np.array([x, probs])

print('Рассмотрим случайный вектор с таблицей совместного распределения')
display(tabulate(probs, tablefmt='html', showindex=list(x), headers=list(y)) )

Рассмотрим случайный вектор с таблицей совместного распределения


'<table>\n<thead>\n<tr><th style="text-align: right;">  </th><th style="text-align: right;">    0</th><th style="text-align: right;">    1</th><th style="text-align: right;">    2</th></tr>\n</thead>\n<tbody>\n<tr><td style="text-align: right;"> 0</td><td style="text-align: right;">0.055</td><td style="text-align: right;">0.037</td><td style="text-align: right;">0.096</td></tr>\n<tr><td style="text-align: right;"> 1</td><td style="text-align: right;">0.074</td><td style="text-align: right;">0.036</td><td style="text-align: right;">0.302</td></tr>\n<tr><td style="text-align: right;"> 2</td><td style="text-align: right;">0.129</td><td style="text-align: right;">0.085</td><td style="text-align: right;">0.186</td></tr>\n</tbody>\n</table>'

Матрица вероятностей $\mathcal P = (f(x,y))$

In [42]:
print(probs)

[[0.055 0.037 0.096]
 [0.074 0.036 0.302]
 [0.129 0.085 0.186]]


## Маргинальные распределения

Для $X_1$ маргинальные вероятности $f_1(x)=\sum_y f(x,y)$

In [43]:
probs1 = probs.sum(axis=1)
probs1

array([0.188, 0.412, 0.4  ])

Математическое оживание $E(X_1)=\sum_x xf_1(x)$

In [44]:
np.sum(x*probs1)

np.float64(1.212)

Для $X_2$ маргинальные вероятности $f_2(y)=\sum_x f(x,y)$

In [45]:
probs2 = probs.sum(axis=0)
probs2

array([0.258, 0.158, 0.584])

Математическое оживание $E(X_2)=\sum_y yf_2(y)$

In [46]:
np.sum(y*probs2)

np.float64(1.326)

## Ковариация и корреляция

Вычислим $E(X_1X_2)=\sum_{x,y} xyf(x,y)=x^\top \mathcal{P} y$

In [47]:
x.T@probs@y

np.float64(1.5540000000000003)

Ковариация $cov(X_1,X_2)=E(X_1X_2)-E(X_1)E(X_2)$

In [48]:
x.T@probs@y-(x.T@probs1)*(y.T@probs2)

np.float64(-0.053111999999999826)

Корреляция 

$$
	corr(X_1,X_2)=\frac{cov(X_1,X_2)}{\sqrt{Var(X_1)Var(X_2)}}
$$

In [49]:
var1 = np.sum((x**2)*probs1)-np.sum(x*probs1)**2
var2 = np.sum((y**2)*probs2)-np.sum(y*probs2)**2

(x.T@probs@y-(x.T@probs1)*(y.T@probs2))/((var1*var2)**0.5)

np.float64(-0.08402584444732031)

## Условное распределение и условное математическое распределение

Найдем распределением $X_1$ при условии $X_2=1$

$$
\begin{aligned}
	f_1(x|1)&=\frac{f(x,1)}{f_2(1)} & f_2(1)&=\sum_x f(x,1)
\end{aligned}
$$

In [50]:
cond_probs1 = probs[:,y==1].T/np.sum(probs[:,y==1].T)
cond_probs1

array([[0.23417722, 0.2278481 , 0.53797468]])

Условное математическое ожидание 

$$
	E(X_1|X_2=1)=\sum_x xf_1(x|1)
$$

In [51]:
np.sum(x*cond_probs1)

np.float64(1.3037974683544302)

Найдем распределением $X_2$ при условии $X_1=2$

$$
\begin{aligned}
	f_2(y|2)&=\frac{f(2,y)}{f_1(2)} & f_1(2)&=\sum_y f(2,y)
\end{aligned}
$$

In [52]:
cond_probs2 = probs[x==2,:]/np.sum(probs[x==2,:])
cond_probs2

array([[0.3225, 0.2125, 0.465 ]])

Условное математическое ожидание 

$$
	E(X_2|X_1=2)=\sum_y yf_1(y|2)
$$

In [53]:
np.sum(y*cond_probs2)

np.float64(1.1425)